### ISSUE TITLE
Ethernet support?

### ISSUE THREAD

**Issue by FSund** [ansarid/pysicktim#2]
Do you have any plans to add support for interaction via the ethernet connection? Or any ideas around a strategy for how this could be achieved?

I am working with the TiM571, but I imagine the approach would be similar for the 561.

**Comment by ansarid** [comment]
@FSund I'd like to do that but unfortunately I don't have an ethernet cable for my device that I could use to develop on. I may attempt making my own cable. But otherwise, the library does have most of the functionality over USB.

**Comment by FSund** [comment]
Yeah I'm not worried about functionality, more that it seems like the intended connection method is the ethernet/circular connector, while the USB is more for debugging and setup. I don't think the device even counts as waterproof/IP67 if the USB cover is open.

I might have a look at figuring this out myself, since I'd rather not use ROS or the SOPAS tool if I can avoid it.

The cable itself should be easy enough to make yourself if you have the right connector. It's something like this (check the male/female section though, I don't have the device with me right now to confirm) https://www2.mouser.com/ProductDetail/Amphenol-LTW/MSDS-04BMMC-SL7001?qs=bZr6mbWTK5lRdfeDNHd55Q%3D%3D

**Comment by ansarid** [comment]
Yeah, I wrote this library so that I could avoid using ROS. I'll look into making one of those cables. I do need to make other changes to this library like bundling the library functions into a class to that it would be easier to communicate with multiple lidars through this library as well as for general coding good practice.

I'd also be happy to merge a fork if you forked this library and implemented the ethernet communication functionality.

**Comment by FSund** [comment]
I found something that might be used as a starting point for getting data via TCP: https://github.com/SICKAG/sick_scan/blob/master/tools/sick_generic_device_finder/sick_generic_device_finder.py

I think this is made by SICK themselves.

I also found a TiM561 Python driver here which seems to use TCP https://github.com/cvra/tim561_lidar_driver

**Comment by FSund** [comment]
A quick update: I ended up using the tim561 code from cvra I linked above, just ripping out the zmqmsgbus since I didn't need that. Turns out you only need the socket stuff and an IP address and you're good to go. I don't see myself doing making a PR to your code in the near future, so feel free to close this issue.

**Comment by ansarid** [comment]
@FSund Thanks for the update! I'm glad you found something! Good luck!
