### ISSUE TITLE
AttributeError with TIM361 on RPi

### ISSUE THREAD

**Issue by lbbettinger** [ansarid/pysicktim#4]
**SICK TIM361 connected via USB to RPi 4**
lsusb:
```
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 19a2:5001
Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
**Modules installed via pip3:**
pyusb 1.2.1
pysicktim 0.0.9

**Running scan_example.py returns:**
```
Traceback (most recent call last):
  File "scan_example.py", line 11, in <module>
    print(lidar.scan.distances) # print distance list
AttributeError: 'function' object has no attribute 'distances'
```

**Comment by dmalawey** [comment]
@ansarid can you help us out with this issue?  Our team is working with the SICK tim361.

**Comment by lbbettinger** [comment]
According to SICK the TIM3xx LiDARs do not support ranging data output over USB or TCP on firmwares >=2.50. Our TIM361 is on firmware 2.59 so that explains the issues with pysicktim.

Closing issue.
