### ISSUE TITLE
NanoScan3

### ISSUE THREAD

**Issue by gabriel-wainmann** [ansarid/pysicktim#6]
Hi

Would you please make one of these for the Sick NanoScan3?

Thanks

**Comment by ansarid** [comment]
@gabriel-wainmann I'd love too if I had access to a SICK NanoScan3, but I don't. :(
Also, this library is desperately in need of being rewritten, since it's written quite awfully to be quite honest. But I haven't had the time to do that.

Thanks for the suggestion though!
